version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: devj
      POSTGRES_PASSWORD: smp8074
      POSTGRES_DB: somap
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d # Volumen para inicializar la base de datos


  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: devj
      DB_PASSWORD: smp8074
      DB_NAME: somap
      JWT_SECRET: your_secret_key
      JWT_EXPIRES_IN: 1h
    depends_on:
      - db

volumes:
  pgdata:
